include("test_utils.jl")
include("test_basic.jl")
include("test_from_dict.jl")
include("test_reflection.jl")
include("test_issue50.jl")
include("test_reflected.jl")
include("test_auto_maybe_default.jl")
